### ISSUE TITLE
Joomla 3.4 compatibility issue?

### ISSUE THREAD

**Issue by esedic** [svenbluege/plg_ace_editor#1]
I'm using editor version 0.0.8 on Joomla 3.3.6.
Everything was working ok.
After updating site to Joomla 3.4, I couldn't save changes in custom HTML module. Page is reloaded but changes I've made in editor are not saved.

Then I've updated editor to latest code from Github repository (0.0.10). Then when I tried to click on save button, I get javascript error: Uncaught TypeError: Cannot read property 'aceEditor' of undefined

**Comment by svenbluege** [comment]
Joomla does not load MooTools by default anymore. Because if this the editor fails.

**Comment by svenbluege** [comment]
do you mind trying again? I added a fix but this one seems to be unrelated to a Joomla 3.4 update.

**Comment by esedic** [comment]
I still get an error on save (accidentally closed this issue, so I've reopened it).

**Comment by svenbluege** [comment]
Can you check if you've got the fix I made with the last commit?

**Comment by esedic** [comment]
Yep. The change is there.

**Comment by svenbluege** [comment]
try again please

**Comment by esedic** [comment]
Now it's working.

Thanks!
